# render.yaml  –  Render Infrastructure-as-Code config
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: cicd-demo-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true          # Render also auto-deploys on every push to main
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
